---
# minimal_bashrc/tasks/main.yml

- name: 'Set primary group to users on SUSE/openSUSE'
  ansible.builtin.set_fact:
    primary_group_name: 'users'
  when: '
    ansible_distribution == "SLES" or
    ansible_distribution == "openSUSE Leap" or
    ansible_distribution == "openSUSE MicroOS" or
    ansible_distribution == "openSUSE Tumbleweed"
    '

- name: 'Create .bashrc for root'
  ansible.builtin.template:
    src: 'bashrc.j2'
    dest: '/root/.bashrc'
    owner: 'root'
    group: 'root'
    mode: '0644'
  when:
    - bashrc_for_root | bool

- name: 'Create .bashrc for other users (if any are supplied)'
  ansible.builtin.template:
    src: 'bashrc.j2'
    dest: "/home/{{ item }}/.bashrc"
    owner: "{{ item }}"
    group: "{{ primary_group_name | default(item) }}"
    mode: '0644'
  with_items:
    - "{{ additional_users }}"
  when: 'additional_users is defined'
